### ISSUE TITLE
Mirroring content

### ISSUE THREAD

**Issue by salikadave** [naikshubham14/VirtualWhiteboard#1]
Hey there, nice project idea. I was curious to know that if one writes an equation in the air, does it get mirrored to the user watching the video?

Also, consider adding a `requirements.txt` and some instructions to run this project.

**Comment by naikshubham14** [comment]
Yes everything you write on the board is flipped horizontally. 
The video posted is flipped again while editing.
And thanks for reminding me about the requirements.txt had forgot about that.

**Comment by salikadave** [comment]
Great work!
